ny = read.csv('new-york-city.csv')
wash = read.csv('washington.csv')
chi = read.csv('chicago.csv')
head(ny)
ggplot(aes(x = Trip.Duration/60), data = ny) + geom_histogram(binwidth = 1, col = "blue") + scale_x_continuous(limits = c(0,60), breaks = seq(0, 60, 10)) + geom_vline(xintercept = median(ny$Trip.Duration/60), col = "pink") + ggtitle('Total Travel Time of Bikeshare Users in New York City') + xlab('Total Trip Duration (Minutes)') + ylab('Number of Users')
summary(ny$Trip.Duration/60)
ggplot(aes(x = Trip.Duration/60), data = chi) + geom_histogram(binwidth = 1, fill = "red", col = 'gray') + scale_x_continuous(limits = c(0,60), breaks = seq(0, 60, 10)) + geom_vline(xintercept = median(chi$Trip.Duration/60), col = "purple") + ggtitle('Total Travel Time of Bikeshare Users in Chicago') + xlab('Total Trip Duration (Minutes)') + ylab('Number of Users')
summary(chi$Trip.Duration/60)
ggplot(aes(x = Trip.Duration/60), data = wash) + geom_histogram(binwidth = 1, fill = "gold", col = 'gray') + scale_x_continuous(limits = c(0,60), breaks = seq(0, 60, 10)) + geom_vline(xintercept = median(wash$Trip.Duration/60), col = "blue") + ggtitle('Total Travel Time of Bikeshare Users in Washington DC') + xlab('Total Trip Duration (Minutes)') + ylab('Number of Users')
summary(wash$Trip.Duration/60)
